services:
  hotel-mysql:
    image: mysql:latest
    restart: always
    container_name: hotelsql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB}

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

    ports:
      - "3306:3306"

    volumes:
      - hotel_volume:/var/lib/mysql
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hotel-net

  backend:
    build: ./server
    container_name: hotel-backend
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB}
      JWT_SECRET: ${JWT_SECRET}
    depends_on: 
      hotel-mysql:
        condition: service_healthy
    networks: 
     - hotel-net


  frontend:
    build: ./client
    container_name: hotel-frontend
    ports:
      - "5173:5173"
    networks: 
     - hotel-net

volumes:
  hotel_volume:

networks:
  hotel-net:
    driver: bridge
