kind: Pod
apiVersion: v1

metadata:
  name: backend-pod
  namespace: hotel-namespace
  labels:
    app: backend

spec:
  containers:
    - name: backend
      image: hotel-management-system-backend:latest   #dannysdockerhub/hotel-server
      imagePullPolicy: Never
      ports:
        - containerPort: 5000
      env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: all-secret
              key: MYSQL_HOST

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: all-secret
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: all-secret
              key: MYSQL_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: MYSQL_DATABASE

        - name: JWT_SECRATE
          valueFrom:
            secretKeyRef:
              name: all-secret
              key: JWT_SECRATE

