kind: Pod
apiVersion: v1

metadata:
  name: frontend-pod
  namespace: hotel-namespace
  labels: 
    app: frontend

spec:
  containers:
    - name: frontend
      image: hotel-management-system-frontend:latest  #dannysdockerhub/hotel-client
      imagePullPolicy: Never
      ports:
        - containerPort: 5173





