apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: hotel-namespace

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: hotel-management-system-frontend:latest   #dannysdockerhub/hotel-client
          imagePullPolicy: Never
          ports:
            - containerPort: 5173

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "400m"
