kind: Pod
apiVersion: v1

metadata:
  name: mysql-pod
  namespace: hotel-namespace
  labels:
    app: mysql

spec:
  containers:
    - name: mysql
      image: mysql:latest
      imagePullPolicy: Never
      ports: 
        - containerPort: 3306
      env: 
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: all-secret
            key: MYSQL_ROOT_PASSWORD

      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: all-secret
            key: MYSQL_DATABASE
